name: weekly scrape

on:
  schedule:
    # Monday at 06:00 UTC
    - cron: '0 6 * * 1'
  workflow_dispatch: {}

jobs:
  hit-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call scraping endpoint
        run: |
          set -e
          echo "Hitting $SCRAPE_URL" 
          curl -fsSL "$SCRAPE_URL" -m 120 -o response.json
          cat response.json
    env:
      SCRAPE_URL: ${{ secrets.SCRAPE_URL }}
